### ISSUE TITLE
获取发行版错误 之前安装成功的 今天看有更新 是不是哪里错了

### ISSUE THREAD

**Issue by AIEOV** [biliup-start/biliup-start#1]
centos7的机器提示不能用apt
ubuntu22的提示不支持的发行版 但是我之前安装的机子一模一样  辛苦作者看下是不是哪里不太对

**Comment by ikun1993** [comment]
额，好的我看看

**Comment by ikun1993** [comment]
你重新试了  我更新错了版本

**Comment by ikun1993** [comment]
#https://github.com/ikun1993/biliupstart/releases/download/V0.21/start.sh
